package co.mailtarget.emailspamchecker.resource

/**
 * Created by ciazhar on 19/02/18.
 * [ Documentatiion Here ]
 */

object TriggerWord {

    val english = mutableListOf(
        "100%",
        "#1",
        "$$$",
        "100% free",
        "100% Satisfied",
        "4U",
        "50% off",
        "Accept credit cards",
        "Acceptance",
        "Access",
        "Accordingly",
        "Act Now",
        "Action",
        "Ad",
        "Additional income",
        "Addresses",
        "Affordable",
        "All natural",
        "All new",
        "Amazed",
        "Amazing",
        "Amazing stuff",
        "Apply now",
        "Apply Online",
        "As seen on",
        "Auto email removal",
        "Avoid",
        "Avoid bankruptcy",
        "Bargain",
        "Be amazed",
        "Be your own boss",
        "Being a member",
        "Beneficiary",
        "Best price",
        "Beverage",
        "Big bucks",
        "Bill 1618",
        "Billing",
        "Billing address",
        "Billion",
        "Billion dollars",
        "Bonus",
        "Boss",
        "Brand new pager",
        "Bulk email",
        "Buy",
        "Buy direct",
        "Buying judgments",
        "Cable converter",
        "Call",
        "Call free",
        "Call now",
        "Calling creditors",
        "Can’t live without",
        "Cancel",
        "Cancel at any time",
        "Cannot be combined with any other offer",
        "Cards accepted",
        "Cash",
        "Cash bonus",
        "Cashcashcash",
        "Casino",
        "Celebrity",
        "Cell phone cancer scam",
        "Cents on the dollar",
        "Certified",
        "Chance",
        "Cheap",
        "Check",
        "Check or money order",
        "Claims",
        "Claims not to be selling anything",
        "Claims to be in accordance with some spam law",
        "Claims to be legal",
        "Clearance",
        "Click",
        "Click below",
        "Click here",
        "Click to remove",
        "Collect",
        "Collect child support",
        "Compare",
        "Compare rates",
        "Compete for your business",
        "Confidentially on all orders",
        "Congratulations",
        "Consolidate debt and credit",
        "Consolidate your debt",
        "Copy accurately",
        "Copy DVDs",
        "Costs",
        "Credit",
        "Credit bureaus",
        "Credit card",
        "Cures offers",
        "Cures baldness",
        "Deal",
        "Dear",
        "Debt",
        "Diagnostics",
        "Dig up dirt on friends",
        "Direct email",
        "Direct marketing",
        "Discount",
        "Do it today",
        "Don’t delete",
        "Don’t hesitate",
        "Dormant",
        "Double your",
        "Double your cash",
        "Double your income",
        "Drastically reduced",
        "Earn",
        "Earn $",
        "Earn extra cash",
        "Earn per week",
        "Easy terms",
        "Eliminate bad credit",
        "Eliminate debt",
        "Email harvest",
        "Email marketing",
        "Exclusive deal",
        "Expect to earn",
        "Expire",
        "Explode your business",
        "Extra",
        "Extra cash",
        "Extra income",
        "F r e e",
        "Fantastic",
        "Fantastic deal",
        "Fast cash",
        "Fast",
        "Viagra delivery",
        "Financial freedom",
        "Financially independent",
        "For free",
        "For instant access",
        "For just",
        "For Only",
        "For you",
        "Form",
        "Free",
        "Free access",
        "Free cell phone",
        "Free consultation",
        "Free DVD",
        "Free gift",
        "Free grant money",
        "Free hosting",
        "Free info",
        "Free installation",
        "Free Instant",
        "Free investment",
        "Free leads",
        "Free membership",
        "Free money",
        "Free offer",
        "Free preview",
        "Free priority mail",
        "Free quote",
        "Free sample",
        "Free trial",
        "Free website",
        "Freedom",
        "Friend",
        "Full refund",
        "Get",
        "Get it now",
        "Get out of debt",
        "Get paid",
        "Get started now",
        "Gift certificate",
        "Give it away",
        "Giving away",
        "Great",
        "Great offer",
        "Guarantee",
        "Guaranteed",
        "Have you been turned down?",
        "Hello",
        "Here",
        "Hidden",
        "Hidden assets",
        "Hidden charges",
        "Home",
        "Home based",
        "Home employment",
        "Home based business",
        "Human growth hormone",
        "If only it were that easy",
        "Important information regarding",
        "In accordance with laws",
        "Income",
        "Income from home",
        "Increase sales",
        "Increase traffic",
        "Increase your sales",
        "Incredible deal",
        "Info you requested",
        "Information you requested",
        "Instant",
        "Insurance",
        "Internet market",
        "Internet marketing",
        "Investment",
        "Investment",
        "It’s decision effective",
        "Join millions",
        "Join millions of Americans",
        "Junk",
        "Laser printer",
        "Leave",
        "Legal",
        "Life",
        "Life Insurance",
        "Lifetime",
        "Limited",
        "Limited time offer",
        "Limited time only",
        "Loan",
        "Long distance phone offer",
        "Lose",
        "Lose weight",
        "Lose weight spam",
        "Lower interest rates",
        "Lower monthly payment",
        "Lower your mortgage rate",
        "Lowest insurance rates",
        "Lowest Price",
        "Luxury",
        "Luxury car",
        "Mail in order form",
        "Maintained",
        "Make $",
        "Make money",
        "Marketing",
        "Marketing solutions",
        "Mass email",
        "Medicine",
        "Medium",
        "Meet singles",
        "Member",
        "Member stuff",
        "Message contains",
        "Message contains disclaimer",
        "Million",
        "Million dollars",
        "Miracle",
        "MLM",
        "Money",
        "Money back",
        "Money making",
        "Month trial offer",
        "More Internet Traffic",
        "Mortgage",
        "Mortgage rates",
        "Multi­level marketing",
        "Name brand",
        "Never",
        "New customers only",
        "New domain extensions",
        "Nigerian",
        "No age restrictions",
        "No catch",
        "No claim forms",
        "No cost",
        "No credit check",
        "No disappointment",
        "No experience",
        "No fees",
        "No gimmick",
        "No hidden",
        "No hidden Costs",
        "No interests",
        "No inventory",
        "No investment",
        "No medical exams",
        "No middleman",
        "No obligation",
        "No purchase necessary",
        "No questions asked",
        "No selling",
        "No strings attached",
        "No­ obligation",
        "Not intended",
        "Not junk",
        "Not spam",
        "Now",
        "Now only",
        "Obligation",
        "Offshore",
        "Offer",
        "Offer expires",
        "Once in lifetime",
        "One hundred percent free",
        "One hundred percent guaranteed",
        "One time",
        "One time mailing",
        "Online biz opportunity",
        "Online degree",
        "Online marketing",
        "Online pharmacy",
        "Only",
        "Only $",
        "Open",
        "Opportunity",
        "Opt in",
        "Order",
        "Order now",
        "Order shipped by",
        "Order status",
        "Order today",
        "Outstanding values",
        "Passwords",
        "Pennies a day",
        "Per day",
        "Per week",
        "Performance",
        "Phone",
        "Please read",
        "Potential earnings",
        "Pre­approved",
        "Presently",
        "Price",
        "Print form signature",
        "Print out and fax",
        "Priority mail",
        "Prize",
        "Problem",
        "Produced and sent out",
        "Profits",
        "Promise",
        "Promise you",
        "Purchase",
        "Pure Profits",
        "Quote",
        "Rates",
        "Real thing",
        "Refinance",
        "Refinance home",
        "Refund",
        "Removal",
        "Removal instructions",
        "Remove",
        "Removes wrinkles",
        "Request",
        "Requires initial investment",
        "Reserves the right",
        "Reverses",
        "Reverses aging",
        "Risk free",
        "Rolex",
        "Round the world",
        "S 1618",
        "Safeguard notice",
        "Sale",
        "Sample",
        "Satisfaction",
        "Satisfaction guaranteed",
        "Save $",
        "Save big money",
        "Save up to",
        "Score",
        "Score with babes",
        "Search engine listings",
        "Search engines",
        "Section 301",
        "See for yourself",
        "Sent in compliance",
        "Serious",
        "Serious cash",
        "Serious only",
        "Shopper",
        "Shopping spree",
        "Sign up free today",
        "Social security number",
        "Solution",
        "Spam",
        "Special promotion",
        "Stainless steel",
        "Stock alert",
        "Stock disclaimer statement",
        "Stock pick",
        "Stop",
        "Stop snoring",
        "Strong buy",
        "Stuff on sale",
        "Subject to cash",
        "Subject to credit",
        "Subscribe",
        "Success",
        "Supplies",
        "Supplies are limited",
        "Take action",
        "Take action now",
        "Talks about hidden charges",
        "Talks about prizes",
        "Teen",
        "Tells you it’s an ad",
        "Terms",
        "Terms and conditions",
        "The best rates",
        "The following form",
        "They keep your money",
        "No refund",
        "They’re just giving it away",
        "This isn’t a scam",
        "This isn’t junk",
        "This isn’t spam",
        "This won’t last",
        "Thousands",
        "Time limited",
        "Traffic",
        "Trial",
        "Undisclosed recipient",
        "University diplomas",
        "Unlimited",
        "Unsecured credit",
        "Unsecured debt",
        "Unsolicited",
        "Unsubscribe",
        "Urgent",
        "US dollars",
        "Vacation",
        "Vacation offers",
        "Valium",
        "Viagra",
        "Vicodin",
        "Visit our website",
        "Wants credit card",
        "Warranty",
        "We hate spam",
        "We honor all",
        "Web traffic",
        "Weekend getaway",
        "Weight",
        "Weight loss",
        "What are you waiting for?",
        "What’s keeping you?",
        "While supplies last",
        "While you sleep",
        "Who really wins?",
        "Why pay more?",
        "Wife",
        "Will not believe your eyes",
        "Win",
        "Winner",
        "Winning",
        "Won",
        "Work from home",
        "Xanax",
        "You are a winner!",
        "You have been selected",
        "Your income"
    )

    val bahasa = mutableListOf(
        "100%",
        "# 1",
        "$$$",
        "100% gratis",
        "100% Puas",
        "4U",
        "diskon 50",
        "Terima kartu kredit",
        "Penerimaan",
        "Mengakses",
        "Demikian",
        "Bertindak sekarang",
        "Tindakan",
        "Iklan",
        "Pendapatan tambahan",
        "Alamat",
        "Terjangkau",
        "Semua alami",
        "Semuanya baru",
        "Takjub",
        "Menakjubkan",
        "Hal yang menakjubkan",
        "Terapkan sekarang",
        "Terapkan Online",
        "Seperti yang terlihat pada",
        "Penghapusan email otomatis",
        "Menghindari",
        "Hindari kebangkrutan",
        "Tawar",
        "Terkesima",
        "Jadilah bosmu sendiri",
        "Menjadi anggota",
        "Penerima",
        "Harga terbaik",
        "Minuman",
        "Big bucks",
        "Bill 1618",
        "Penagihan",
        "Alamat tagihan",
        "Milyar",
        "Miliar dolar",
        "Bonus",
        "Bos",
        "Brand new pager",
        "Email massal",
        "Membeli",
        "Beli langsung",
        "Membeli penghakiman",
        "Konverter kabel",
        "Panggilan",
        "Bebas panggilan",
        "Telepon sekarang",
        "Memanggil kreditor",
        "Tidak bisa hidup tanpa",
        "Membatalkan",
        "Batalkan kapan saja",
        "Tidak bisa digabungkan dengan penawaran lain",
        "Kartu diterima",
        "Kas",
        "Bonus tunai",
        "Cashcashcash",
        "Kasino",
        "Selebriti",
        "Cell phone cancer scam",
        "Sen pada dolar",
        "Bersertifikat",
        "Kesempatan",
        "Murah",
        "Memeriksa",
        "Cek atau money order",
        "Klaim",
        "Klaim tidak menjual apapun",
        "Klaim harus sesuai dengan beberapa undang-undang spam",
        "Klaim itu legal",
        "Izin",
        "Klik",
        "Klik di bawah",
        "Klik disini",
        "Klik untuk menghapus",
        "Mengumpulkan",
        "Kumpulkan dukungan anak",
        "Membandingkan",
        "Bandingkan harga",
        "Bersaing untuk bisnis Anda",
        "Yakin pada semua pesanan",
        "Selamat",
        "Mengkonsolidasikan hutang dan kredit",
        "Konsolidasi hutang Anda",
        "Copy akurat",
        "Copy DVD",
        "Biaya",
        "Kredit",
        "Biro kredit",
        "Kartu kredit",
        "Cures menawarkan",
        "Menyembuhkan kebotakan",
        "Berurusan",
        "Sayang",
        "Hutang",
        "Diagnostik",
        "Menggali kotoran pada teman",
        "Email langsung",
        "Pemasaran langsung",
        "Diskon",
        "Lakukan hari ini",
        "Jangan hapus",
        "Jangan ragu",
        "Terbengkalai",
        "Double your",
        "Gandakan uang Anda",
        "Ganda penghasilan Anda",
        "Secara drastis dikurangi",
        "Dapatkan",
        "Dapatkan $",
        "Dapatkan uang ekstra",
        "Dapatkan per minggu",
        "Istilah mudah",
        "Hilangkan kredit macet",
        "Hilangkan hutang",
        "Email panen",
        "Email Pemasaran",
        "Kesepakatan eksklusif",
        "Berharap untuk mendapatkan",
        "Berakhir",
        "Meledak bisnis Anda",
        "Tambahan",
        "Uang tambahan",
        "Penghasilan tambahan",
        "Bebas",
        "Fantastis",
        "Kesepakatan yang fantastis",
        "Uang cepat",
        "Cepat",
        "Pengiriman Viagra",
        "Kebebasan finansial",
        "Independen secara finansial",
        "Gratis",
        "Untuk akses instan",
        "Hanya untuk",
        "Hanya untuk",
        "Untukmu",
        "Bentuk",
        "Bebas",
        "Akses gratis",
        "Ponsel gratis",
        "Konsultasi gratis",
        "DVD gratis",
        "Hadiah gratis",
        "Uang hibah gratis",
        "Hosting GRATIS",
        "Info gratis",
        "Instalasi gratis",
        "Instan Gratis",
        "Investasi gratis",
        "Free lead",
        "Keanggotaan GRATIS",
        "Gratis",
        "Penawaran gratis",
        "Pratinjau gratis",
        "Email prioritas gratis",
        "Kutipan gratis",
        "Sampel gratis",
        "Percobaan gratis",
        "Situs gratis",
        "Kebebasan",
        "Teman",
        "Pengembalian dana penuh",
        "Mendapatkan",
        "Dapatkan itu sekarang",
        "Menuntaskan hutang",
        "Dibayar",
        "Mulai sekarang",
        "Sertifikat hadiah",
        "Berikan itu",
        "Memberikan",
        "Besar",
        "Penawaran Hebat",
        "Menjamin",
        "Terjamin",
        "Sudahkah kamu ditolak?",
        "Halo",
        "Sini",
        "Tersembunyi",
        "Aset tersembunyi",
        "Tuduhan Tersembunyi",
        "Rumah",
        "Berbasis rumah",
        "Pekerjaan di rumah",
        "Bisnis berbasis rumah",
        "Hormon pertumbuhan manusia",
        "Kalau saja semudah itu",
        "Informasi penting mengenai",
        "Sesuai dengan hukum",
        "Pendapatan",
        "Penghasilan dari rumah",
        "Meningkatkan penjualan",
        "Meningkatkan trafik",
        "Tingkatkan penjualan Anda",
        "Kesepakatan yang luar biasa",
        "Info yang anda minta",
        "Informasi yang Anda minta",
        "Instan",
        "Asuransi",
        "Pasar internet",
        "Pemasaran internet",
        "Investasi",
        "Investasi",
        "Ini keputusan yang efektif",
        "Bergabunglah dengan jutaan orang Amerika",
        "Junk",
        "Printer laser",
        "Meninggalkan",
        "Hukum",
        "Kehidupan",
        "Asuransi jiwa",
        "Seumur hidup",
        "Terbatas",
        "Penawaran terbatas",
        "Terbatas waktu saja",
        "Pinjaman",
        "Penawaran telepon jarak jauh",
        "Kalah",
        "Menurunkan berat badan",
        "Menurunkan berat badan spam",
        "Suku bunga yang lebih rendah",
        "Menurunkan pembayaran bulanan",
        "Turunkan tingkat hipotek Anda",
        "Tingkat asuransi terendah",
        "Harga Terendah",
        "Kemewahan",
        "Mobil mewah",
        "Mail dalam bentuk pesanan",
        "Terawat",
        "Buat $",
        "Menghasilkan uang",
        "Pemasaran",
        "Solusi pemasaran",
        "Email massal",
        "Obat",
        "Medium",
        "Meet single",
        "Anggota",
        "Barang anggota",
        "Pesan berisi",
        "Pesan berisi disclaimer",
        "Juta",
        "Juta dolar",
        "Keajaiban",
        "MLM",
        "Uang",
        "Uang kembali",
        "Pembuatan uang",
        "Bulan uji coba",
        "Lalu Lintas Internet Lainnya",
        "Hipotek",
        "Tingkat hipotek",
        "Pemasaran multilevel",
        "Nama merek",
        "Tak pernah",
        "Pelanggan baru saja",
        "Ekstensi domain baru",
        "Nigeria",
        "Tidak ada batasan umur",
        "Tidak menangkap",
        "Tidak ada formulir klaim",
        "Tidak ada biaya",
        "Tidak ada pemeriksaan kredit",
        "Tidak mengecewakan",
        "Tidak berpengalaman",
        "Tanpa biaya",
        "Tidak ada gimmick",
        "Tidak tersembunyi",
        "Tidak ada biaya tersembunyi",
        "Tidak ada kepentingan",
        "Tidak ada persediaan",
        "Tidak ada investasi",
        "Tidak ada ujian medis",
        "Tidak ada perantara",
        "Tidak ada kewajiban",
        "Tidak ada pembelian yang diperlukan",
        "Tidak ada pertanyaan yang ditanyakan",
        "Tidak menjual",
        "Tidak ada senar yang terpasang",
        "Tidak ada kewajiban",
        "Tidak dimaksudkan",
        "Bukan sampah",
        "Bukan spam",
        "Sekarang",
        "Hanya sekarang",
        "Kewajiban",
        "Di lepas pantai",
        "Menawarkan",
        "Penawaran kedaluwarsa",
        "Sekali dalam seumur hidup",
        "Seratus persen gratis",
        "Seratus persen dijamin",
        "Satu kali",
        "Satu kali pengiriman",
        "Peluang biz online",
        "Gelar online",
        "Pemasaran online",
        "Apotek daring",
        "Hanya",
        "Hanya $",
        "Buka",
        "Kesempatan",
        "Memilih di",
        "Memesan",
        "Pesan sekarang",
        "Order dikirim oleh",
        "Status pemesanan",
        "Pesan hari ini",
        "Nilai yang luar biasa",
        "Sandi",
        "Pennies sehari",
        "Per hari",
        "Per minggu",
        "Kinerja",
        "Telepon",
        "Silakan baca",
        "Potensi penghasilan",
        "Preapproved",
        "Sekarang",
        "Harga",
        "Tanda tangan formulir cetak",
        "Cetak dan faks",
        "Priority mail",
        "Hadiah",
        "Masalah",
        "Diproduksi dan dikirim",
        "Keuntungan",
        "Janji",
        "Berjanji padamu",
        "Membeli",
        "Keuntungan Murni",
        "Kutipan",
        "Tarif",
        "Hal yang nyata",
        "Refinance",
        "Refinance home",
        "Pengembalian dana",
        "Pemindahan",
        "Instruksi penghapusan",
        "Menghapus",
        "Menghapus keriput",
        "Permintaan",
        "Membutuhkan investasi awal",
        "Cadangan yang benar",
        "Pembalikan",
        "Membalikkan penuaan",
        "Bebas resiko",
        "Rolex",
        "Keliling dunia",
        "S 1618",
        "Safeguard notice",
        "Penjualan",
        "Mencicipi",
        "Kepuasan",
        "Kepuasan terjamin",
        "Hemat $",
        "Hemat uang besar",
        "Hemat sampai",
        "Skor",
        "Skor dengan babes",
        "Daftar mesin pencari",
        "Mesin pencari",
        "Bagian 301",
        "Lihat diri mu sendiri",
        "Dikirim dalam kepatuhan",
        "Serius",
        "Uang Serius",
        "Serius saja",
        "Pembelanja",
        "Belanja",
        "Daftar gratis hari ini",
        "Nomor KTP",
        "Larutan",
        "Spam",
        "Promosi spesial",
        "Besi tahan karat",
        "Stock alert",
        "Pernyataan disclaimer saham",
        "Stock pick",
        "Berhenti",
        "Berhenti mendengkur",
        "Beli kuat",
        "Barang yang dijual",
        "Tergantung uang tunai",
        "Sesuai dengan kredit",
        "Berlangganan",
        "Keberhasilan",
        "Persediaan",
        "Persediaan terbatas",
        "Mengambil tindakan",
        "Ambil tindakan sekarang",
        "Pembicaraan tentang tuduhan tersembunyi",
        "Pembicaraan tentang hadiah",
        "Remaja",
        "Memberitahu Anda itu sebuah iklan",
        "Persyaratan",
        "Syarat dan ketentuan",
        "Harga terbaik",
        "Bentuk berikut",
        "Mereka menyimpan uang Anda",
        "Tidak ada pengembalian dana",
        "Mereka hanya memberikannya",
        "Ini bukan scam",
        "Ini bukan sampah",
        "Ini bukan spam",
        "Ini tidak akan bertahan",
        "Ribuan",
        "Waktu terbatas",
        "Lalu lintas",
        "Percobaan",
        "Penerima yang tidak diketahui",
        "Ijazah universitas",
        "Tak terbatas",
        "Kredit tanpa jaminan",
        "Utang tanpa jaminan",
        "Tidak diminta",
        "Berhenti berlangganan",
        "Penting",
        "Dolar Amerika",
        "Liburan",
        "Liburan menawarkan",
        "Valium",
        "Viagra",
        "Vicodin",
        "Kunjungi situs web kami",
        "Ingin kartu kredit",
        "Jaminan",
        "Kami membenci spam",
        "Kami menghormati semua",
        "Lalu lintas web",
        "Liburan akhir pekan",
        "Berat",
        "Penurunan berat badan",
        "Apa yang kamu tunggu?",
        "Apa yang membuatmu?",
        "Selama persediaan masih ada",
        "Saat Anda tidur",
        "Siapa yang benar-benar menang?",
        "Mengapa membayar lebih?",
        "Istri",
        "Tidak akan mempercayai matamu",
        "Menang",
        "Pemenang",
        "Kemenangan",
        "Won",
        "Bekerja dari rumah",
        "Xanax",
        "Anda adalah pemenang!",
        "Anda telah terpilih",
        "Penghasilanmu"
    )
}